PRAGMA foreign_keys = ON;

-- =====================================================
-- FUND MASTER
-- =====================================================

CREATE TABLE IF NOT EXISTS fund_master (
amfi_code INTEGER PRIMARY KEY,
fund_house TEXT,
scheme_name TEXT,
category TEXT,
sub_category TEXT,
plan TEXT,
launch_date TEXT,
benchmark TEXT,
expense_ratio_pct REAL,
exit_load_pct REAL,
min_sip_amount REAL,
min_lumpsum_amount REAL,
fund_manager TEXT,
risk_category TEXT,
sebi_category_code TEXT
);

-- =====================================================
-- NAV HISTORY
-- =====================================================

CREATE TABLE IF NOT EXISTS nav_history (
amfi_code INTEGER,
date TEXT,
nav REAL,
PRIMARY KEY (amfi_code, date)
);

-- =====================================================
-- AUM HISTORY
-- =====================================================

CREATE TABLE IF NOT EXISTS aum_history (
date TEXT,
fund_house TEXT,
aum_lakh_crore REAL,
aum_crore REAL,
num_schemes INTEGER
);

-- =====================================================
-- SIP INFLOWS
-- =====================================================

CREATE TABLE IF NOT EXISTS sip_inflows (
month TEXT,
sip_inflow_crore REAL,
active_sip_accounts_crore REAL,
new_sip_accounts_lakh REAL,
sip_aum_lakh_crore REAL,
yoy_growth_pct REAL
);

-- =====================================================
-- CATEGORY INFLOWS
-- =====================================================

CREATE TABLE IF NOT EXISTS category_inflows (
month TEXT,
category TEXT,
net_inflow_crore REAL
);

-- =====================================================
-- FOLIO COUNT
-- =====================================================

CREATE TABLE IF NOT EXISTS folio_count (
month TEXT,
total_folios_crore REAL,
equity_folios_crore REAL,
debt_folios_crore REAL,
hybrid_folios_crore REAL,
others_folios_crore REAL
);

-- =====================================================
-- SCHEME PERFORMANCE
-- Generated by Day 4 Analytics
-- =====================================================
CREATE TABLE IF NOT EXISTS scheme_performance (
    amfi_code INTEGER,
    scheme_name TEXT,
    fund_house TEXT,
    category TEXT,
    plan TEXT,
    return_1yr_pct REAL,
    return_3yr_pct REAL,
    return_5yr_pct REAL,
    benchmark_3yr_pct REAL,
    alpha REAL,
    beta REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    std_dev_ann_pct REAL,
    max_drawdown_pct REAL,
    aum_crore REAL,
    expense_ratio_pct REAL,
    morningstar_rating INTEGER,
    risk_grade TEXT,
    expense_ratio_flag INTEGER
);

-- =====================================================
-- INVESTOR TRANSACTIONS
-- =====================================================

CREATE TABLE IF NOT EXISTS investor_transactions (
investor_id TEXT,
transaction_date TEXT,
amfi_code INTEGER,
transaction_type TEXT,
amount_inr REAL,
state TEXT,
city TEXT,
city_tier TEXT,
age_group TEXT,
gender TEXT,
annual_income_lakh REAL,
payment_mode TEXT,
kyc_status TEXT
);

-- =====================================================
-- PORTFOLIO HOLDINGS
-- =====================================================

CREATE TABLE IF NOT EXISTS portfolio_holdings (
amfi_code INTEGER,
stock_symbol TEXT,
stock_name TEXT,
sector TEXT,
weight_pct REAL,
market_value_cr REAL,
current_price_inr REAL,
portfolio_date TEXT
);

-- =====================================================
-- BENCHMARK INDICES
-- =====================================================

CREATE TABLE IF NOT EXISTS benchmark_indices (
date TEXT,
index_name TEXT,
close_value REAL
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_nav_date
ON nav_history(date);

CREATE INDEX IF NOT EXISTS idx_nav_amfi
ON nav_history(amfi_code);

CREATE INDEX IF NOT EXISTS idx_txn_date
ON investor_transactions(transaction_date);

CREATE INDEX IF NOT EXISTS idx_txn_amfi
ON investor_transactions(amfi_code);

CREATE INDEX IF NOT EXISTS idx_portfolio_amfi
ON portfolio_holdings(amfi_code);

CREATE INDEX IF NOT EXISTS idx_benchmark_date
ON benchmark_indices(date);

CREATE INDEX IF NOT EXISTS idx_benchmark_name
ON benchmark_indices(index_name);
